name = "bluehorizon"
type = "javascript"
workers_dev = true

[[d1_databases]]
binding = "D1"
database_name = "bluehorizon"
database_id = "dfe60d96-f594-41fd-b51d-d0ec6fa34f63"

[site]
bucket = "./public"
